name: Main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit_testing:
    name: "Tests step"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Run unit tests
        run: ./gradlew clean test

  instrumented_testing:
    name: instrumented testing
    runs-on: macos-latest
    timeout-minutes: 25
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: instrumented testing
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          script:
            ./gradlew connectedCheck