name: Main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static_analysis:
    name: "Static analysis step"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Run detekt & detekt ktlint wrapper
        run: ./gradlew clean detekt

      - name: Run android lint
        run: ./gradlew lint

  unit_testing:
    name: "Tests step"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Run unit tests
        run: ./gradlew clean test

  instrumented_testing:
    name: instrumented testing
    runs-on: macos-latest
    timeout-minutes: 25
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: espresso testing
        uses: reactivecircus/android-emulator-runner@v2
        with:
          profile: pixel_3_xl
          api-level: 30
          arch: x86_64
          script:
            ./gradlew connectedCheck

      - name: Upload emulator tests artifacts
        if: always()
        uses: actions/upload-artifact@v2.3.1
        with:
          name: emulator_tests_30
          path: app/build/reports/androidTests